MC-9497 ReferenceDataValue functional specs
MauroDataMapper/mdm-core pull request #126
Opened 2021-08-03 15:53 UTC by adjl

2021-08-04 18:28 UTC, adjl commented
There is a strange bug causing the failures in mdm-plugin-referencedata/ReferenceDataModelFunctionalSpec... All of its tests pass when you run the spec on its own. But when running all tests in the plugin altogether (`gradle :mdm-plugin-referencedata:integrationTest`) it sometimes fails by returning the `referenceDataModel.authority.url` as `https://localhost` instead of `http://localhost`.

Any idea as to the cause? (Flaky test perhaps?)

Regardless, I can't see at a glance how the bug is caused by this PR.

2021-08-06 13:39 UTC, olliefreeman commented
@a

> There is a strange bug causing failures in mdm-plugin-referencedata/ReferenceDataModelFunctionalSpec... All of its tests pass when you run the spec on its own. But when running all tests in the plugin altogether (`gradle :mdm-plugin-referencedata:integrationTest`), it sometimes fails by returning the `referenceDataModel.authority.url` as `https://localhost` instead of `http://localhost`.
> 
> Any idea as to the cause? (Flaky test perhaps?)
> 
> Regardless, I can't see at a glance how the bug is caused by this PR.

You can't run all the integrationTests at the same time as that runs the IT and FT tests.
You either need to run them like the `./run-all-tests.sh` does using gradle
or do as the README instructs and use grails CLI

then 
* `test-app -Dgradle.integrationTest=true -integration` runs the IT 
* `test-app -Dgradle.functionalTest=true -integration` runs the FT

this will probably solve the issue you're finding.

2021-08-06 13:44 UTC, olliefreeman requested changes
We need to review the uniqueness constraint.

We may need to implement a complicated validator but we may be able to get away with the change i propose

2021-08-06 13:44 UTC, olliefreeman commented on mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/provider/XmlReferenceDataImporterExporterServiceSpec.groovy
> +        // Do not load test Reference Data Models because the import is a duplicate and breaks Reference Data Value uniqueness
if the import breaks the uniqueness then there is another issue, as we should be able to import the same model multiple times with different branch names, therefore we got the unique constraint wrong

2021-08-06 13:44 UTC, olliefreeman commented on mdm-plugin-referencedata/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueController.groovy
> +    @Override
protected methods should be below public ones please

2021-08-06 13:44 UTC, olliefreeman commented on mdm-plugin-referencedata/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValue.groovy
> +        value blank: true, nullable: true, unique: 'rowNumber'
we obv got this wrong, you probably want to add `unique: 'rowNumber,referenceDataElement'`

2021-08-06 13:44 UTC, olliefreeman commented on mdm-plugin-referencedata/grails-app/services/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueService.groovy
>          if (!referenceDataValue) return
why have you removed this??

2021-08-06 15:12 UTC, adjl commented on mdm-plugin-referencedata/grails-app/services/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueService.groovy
>          if (!referenceDataValue) return
`breadcrumbTree` is not (no longer?) a property of `ReferenceDataValue`, causing an exception. If there is an alternate way of achieving this, I could comment the statement out and return to it in a separate PR.

2021-08-06 15:13 UTC, adjl commented on mdm-plugin-referencedata/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueController.groovy
> +    @Override
Done

2021-08-06 15:25 UTC, adjl commented on mdm-plugin-referencedata/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValue.groovy
> +        value blank: true, nullable: true, unique: 'rowNumber'
This change causes `BeanCreationException`s and `No GORM implementations configured. Ensure GORM has been initialized correctly`. :/

For the sake of exhaustion, `uniqueness: rowNumber, referenceDataModel` and `uniqueness: rowNumber, referenceDataElement, referenceDataModel` are no good too.

2021-08-06 15:47 UTC, adjl commented on mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/provider/XmlReferenceDataImporterExporterServiceSpec.groovy
> +        // Do not load test Reference Data Models because the import is a duplicate and breaks Reference Data Value uniqueness
For reference, importing with `importAsNewBranchModelVersion = true` still fails and breaks uniqueness.

2021-08-06 16:00 UTC, adjl commented on mdm-plugin-referencedata/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValue.groovy
> +        value blank: true, nullable: true, unique: 'rowNumber'
Silly error. Constraining on two or more fields requires passing them as a list. 🤦‍♀️ `unique: ['rowNumber', 'referenceDataElement']` works.

2021-08-06 16:05 UTC, adjl commented on mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/provider/XmlReferenceDataImporterExporterServiceSpec.groovy
> +        // Do not load test Reference Data Models because the import is a duplicate and breaks Reference Data Value uniqueness
Fixed with the updated `unique` constraint.

2021-08-31 13:02 UTC, olliefreeman approved these changes
looks good

2021-08-31 13:59 UTC, merged