MC-9605 Include imported DataClasses in the tree given a flag
MauroDataMapper/mdm-core pull request #137
Opened 2021-08-25 15:29 UTC by adjl

2021-08-31 13:09 UTC, olliefreeman requested changes
Please make changes as per the comments

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemController.groovy
> +    private boolean shouldIncludeImportedDataClasses() {
mdm-core has no concept of DataClasses, therefore this should be `shouldIncludeImported`

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemService.groovy
> +                                                   boolean includeImportedDataClasses = false) {
as per comment in the controller...the mdm-core base plugin should not include refs to DataClasses, just "imported things"

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemService.groovy
> +            } else new ModelItemTreeItem(mi, mi.hasChildren(), actions, service.isModelItemAnImportedDataClass(mi, catalogueItem))
should be `isModelItemImported`

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/core/rest/transport/tree/ModelItemTreeItem.groovy
> +    boolean importedDataClass
remove ref to DataClass

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/grails-app/views/treeItem/_treeItem.gson
> +        if (miti.isImportedDataClass()) imported miti.importedDataClass
remove ref to DC

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +    boolean isModelItemAnImportedDataClass(ModelItem modelItem, K owningCatalogueItem) {
as we're in the CI service it should be `isCatalogueItemImportedIntoCatalogueItem` and the params should be CatalogueItem catalogueItem, K owningCatalogueItem

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +    boolean hasTreeTypeModelItems(K catalogueItem, boolean fullTreeRender, boolean includeImportedDataClasses) {
refs to DCs

2021-08-31 13:09 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +    List<ModelItem> findAllTreeTypeModelItemsIn(K catalogueItem, boolean fullTreeRender, boolean includeImportedDataClasses) {
refs to DCs

2021-08-31 15:14 UTC, adjl commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemController.groovy
> +    private boolean shouldIncludeImportedDataClasses() {
Done

2021-08-31 15:14 UTC, adjl commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemService.groovy
> +                                                   boolean includeImportedDataClasses = false) {
Done

2021-08-31 15:15 UTC, adjl commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemService.groovy
> +            } else new ModelItemTreeItem(mi, mi.hasChildren(), actions, service.isModelItemAnImportedDataClass(mi, catalogueItem))
Done

2021-08-31 15:15 UTC, adjl commented on mdm-core/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/core/rest/transport/tree/ModelItemTreeItem.groovy
> +    boolean importedDataClass
Done

2021-08-31 15:15 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +    boolean isModelItemAnImportedDataClass(ModelItem modelItem, K owningCatalogueItem) {
Done

2021-08-31 15:15 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +    boolean hasTreeTypeModelItems(K catalogueItem, boolean fullTreeRender, boolean includeImportedDataClasses) {
Done

2021-08-31 15:15 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +    List<ModelItem> findAllTreeTypeModelItemsIn(K catalogueItem, boolean fullTreeRender, boolean includeImportedDataClasses) {
Done

2021-09-01 13:05 UTC, olliefreeman requested changes
When overloading methods where you're adding more and more parameters the method with the most params should be the one which provides the default behaviour. This is so that a user can safely override the largest overload knowing all other methods will fall back into that one. With what you've done, someone would have to override both the 3 and 2 param versions to make sure all eventualities have been covered

2021-09-01 13:05 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +        hasTreeTypeModelItems(catalogueItem, fullTreeRender)
when overloading methods you should always call "up", therefore this is the one which shuold default to false and the 2 param version should call this with includeImportedItems as false

2021-09-01 13:05 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +        findAllTreeTypeModelItemsIn(catalogueItem, fullTreeRender)
same goes for this method, you should always call "up"

2021-09-01 14:38 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +        hasTreeTypeModelItems(catalogueItem, fullTreeRender)
My changes were originally as you suggest, but that was what caused the "TreeItem order" failure:

```groovy
Condition not satisfied:

modelTreeItem.children.collect {it.label} == ['emptyclass', 'integer', 'string', 'child', 'yesnounknown', 'parent', 'content']
|             |        |                  |
|             |        |                  false
|             |        [yesnounknown, emptyclass, integer, string, child, parent, content]
```

How to proceed?

2021-09-02 08:56 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +        hasTreeTypeModelItems(catalogueItem, fullTreeRender)
whatever happens you need to always call "up" we need to work out why the order changes after we fix that .... i will take a look to see if i can see why the order changes

2021-09-02 11:47 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +        hasTreeTypeModelItems(catalogueItem, fullTreeRender)
looking at the code its because various classes extended different versions of the overloaded methods,
i have cleaned up the methods, made sure the overloading is in the right direction and also that all the classes override the correct variant (the largest param version) and then the test doesnt fail.
i will push the change after the next release

2021-09-06 09:15 UTC, olliefreeman requested changes
If you can make the 4 requested changes that should be it and we're good to merge.

2021-09-06 09:15 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelService.groovy
> +    boolean hasTreeTypeModelItems(DataModel dataModel, boolean fullTreeRender, boolean includeImportedDataClasses = false) {
as discussed can you remove the defaults from the params here and let the CIS define the defaults, therefore this method overrides the max param variant

2021-09-06 09:15 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelService.groovy
> +    List<ModelItem> findAllTreeTypeModelItemsIn(DataModel catalogueItem, boolean fullTreeRender = false, boolean includeImportedDataClasses = false) {
as discussed can you remove the defaults from the params here and let the CIS define the defaults, therefore this method overrides the max param variant

2021-09-06 09:15 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
> +    List<ModelItem> findAllTreeTypeModelItemsIn(DataClass dataClass, boolean fullTreeRender = false, boolean includeImportedDataClasses = false) {
as discussed can you remove the defaults from the params here and let the CIS define the defaults, therefore this method overrides the max param variant

2021-09-06 09:15 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
> +    boolean hasTreeTypeModelItems(DataClass dataClass, boolean fullTreeRender, boolean includeImportedDataClasses = false) {
as discussed can you remove the defaults from the params here and let the CIS define the defaults, therefore this method overrides the max param variant

2021-09-09 14:27 UTC, adjl commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelService.groovy
> +    boolean hasTreeTypeModelItems(DataModel dataModel, boolean fullTreeRender, boolean includeImportedDataClasses = false) {
My bad, these files slipped past me somehow.

2021-09-09 14:32 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
>      List<ModelItem> findAllTreeTypeModelItemsIn(K catalogueItem) {
I had to re-add this method because single-param calls still exist in TermService, causing the test failures in the Terminology plugin. Unless it's better to amend those calls instead?

2021-10-04 11:04 UTC, olliefreeman approved these changes

2021-10-04 11:04 UTC, olliefreeman commented
ive pushed a fix to remove the final 3 default parameters from the overriden methods, once the tests have passed i will be happy to merge this

2021-10-04 11:06 UTC, merged