Implement import and export of multiple Data Models, Terminologies and Code Sets in JSON and XML
MauroDataMapper/mdm-core pull request #167
Opened 2021-10-18 16:25 UTC by adjl

2021-10-19 15:22 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/views/exportModel/export.gml
> +    if (exportList.size() > 1) {
in the event its a single export we should render a single model, but if someone uses the "exportModels" endpoint and only provides 1 model id we should export a list as thats what they requested....its important that and endpoint returns the same structure

2021-10-19 15:23 UTC, olliefreeman commented on mdm-core/grails-app/views/exportModel/_exportModel.gson
> +         exportList.size() > 1 ? g.render(template: exportModel.modelExportTemplatePath, collection: exportList, var: 'export')
in the event its a single export we should render a single model, but if someone uses the "exportModels" endpoint and only provides 1 model id we should export a list as thats what they requested....its important that and endpoint returns the same structure

2021-10-19 15:23 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/ExportModel.groovy
> +        this([model], modelType, '', version, version, templatePathFileExtension, exportMetadata)
in the event its a single export we should render a single model, but if someone uses the "exportModels" endpoint and only provides 1 model id we should export a list as thats what they requested....its important that and endpoint returns the same structure

2021-10-20 13:32 UTC, adjl commented on mdm-plugin-datamodel/grails-app/views/exportModel/export.gml
> +    if (exportList.size() > 1) {
Sorry, forgot to revert the structure before opening the PR. Done.

2021-11-01 13:03 UTC, adjl commented on mdm-plugin-terminology/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/terminology/bootstrap/BootstrapModels.groovy
> +    static CodeSet buildAndSaveComplexCodeSet(MessageSource messageSource, Folder folder, TerminologyService terminologyService, Authority authority) {
I thought to add a complex Code Set to make testing consistent with the other models.

What are the requirements for a complex model specifically? In the meantime, the complex Code Set now also pulls from the simple test Terminology as suggested.

2021-12-06 13:57 UTC, olliefreeman commented on mdm-plugin-terminology/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/terminology/bootstrap/BootstrapModels.groovy
> +    static CodeSet buildAndSaveComplexCodeSet(MessageSource messageSource, Folder folder, TerminologyService terminologyService, Authority authority) {
"complex" means "its got a lot more to it" .... its basically to allow a basic sort of testing where we dont have to worry about stuff like nested or facets, and then a complex model which has lots of stuff. in the case of CSs they arent particuraly complex as everything is owned by the terminologies. Therefore the only way i could see a CS as being complex is by pulling terms from multple terminologies, but even this i think is probably unncessary as we have coverage on this with the VF testing.

2021-12-06 14:04 UTC, olliefreeman requested changes
just fix the CS boostrap issue and this is then ready to go...i have gone over everything and thats all thats left

2021-12-08 19:32 UTC, adjl commented on mdm-plugin-terminology/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/terminology/bootstrap/BootstrapModels.groovy
> +    static CodeSet buildAndSaveComplexCodeSet(MessageSource messageSource, Folder folder, TerminologyService terminologyService, Authority authority) {
Done

2021-12-13 10:28 UTC, olliefreeman approved these changes
I just need to rebase this again on develop due to a conflict but i'm happy

2021-12-22 14:20 UTC, merged