Feature/gh 178
MauroDataMapper/mdm-core pull request #194
Opened 2021-11-18 11:40 UTC by aaronforshaw

Add endpoints for bulk retrieval and edit of many profiles against many data elements of a data model.

- POST /dataModels/{dataModelId}/profile/getMany
- POST /dataModels/{dataModelId}/profile/validateMany
- POST /dataModels/{dataModelId}/profile/saveMany

There are examples of the POST bodies added to the postman-library (separate PR).

Although the examples above are for data model, and this PR includes tests for data model, I would expect it also to work for the general case of retrieving and editing profiles against many model items of a model.

The deprecated MapBasedProfile has been removed.

Because the change requires retrieval or save of many resources in one request, this PR includes a slightly new pattern in that most security checks are done in the ProfileController rather than ProfileInterceptor. The pattern in the ProfileController is:
- check that the MultiFacetAwareItem referenced in the URL is a Model
- check that every MultiFacetAwareItem specified in the POST body is a ModelItem which belongs to the Model

2021-11-25 13:48 UTC, olliefreeman commented
i will review this next week....theres a lot going on and i need to sit and work through it

2021-12-01 12:34 UTC, olliefreeman requested changes
A few changes but the logic all looks good

* I have historically used the package `rest.transport` for defining command objects/pogos for binding data in and out of rest json. 
* the _profileProvided.gson should be in /profileProvided/_profileProvided.gson so that grails can auto find it as any class can be found this way where the template is in the folder with that class name. It allows grails to handle any fallback of rendering to use the template we want not a default object template

2021-12-01 12:34 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +            return notFound(params.multiFacetAwareItemClass, params.multiFacetAwareItemId)
can we return a different message/response .. BAD REQUEST if the object is NOT a model please

2021-12-01 12:34 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        ItemsProfilesDataBinding itemsProfiles = new ItemsProfilesDataBinding()
Handy fact...if you use the `ItemsProfilesDataBinding` as a command object...so put it into the method as a param ... ` def getMany(ItemsProfilesDataBinding itemsProfiles) {` it will bind the request into the object for you removing the need for these 2 lines

2021-12-01 12:34 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        ProfileProvidedCollection profileProvidedCollection = new ProfileProvidedCollection()
Use CommandObject please

2021-12-01 12:34 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        itemsProfiles.multiFacetAwareItems.each { multiFacetAwareItemDataBinding ->
i would prefer logic of this scale to be inside a service so the ProfileService, controllers should have as little logic as possible please..so a method inside ProfileService which retrieves a collection of ProfileProvided

2021-12-01 12:34 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        profileProvidedCollection.profilesProvided.each {profileProvided ->
as with getMany please move this scale of logic into teh ProfileService

2021-12-02 16:29 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +            return notFound(params.multiFacetAwareItemClass, params.multiFacetAwareItemId)
Done

2021-12-02 16:30 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        ItemsProfilesDataBinding itemsProfiles = new ItemsProfilesDataBinding()
That is very handy thanks. Done.

2021-12-02 16:30 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +            return notFound(params.multiFacetAwareItemClass, params.multiFacetAwareItemId)
Done

2021-12-02 16:30 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        ProfileProvidedCollection profileProvidedCollection = new ProfileProvidedCollection()
Done

2021-12-02 16:30 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        itemsProfiles.multiFacetAwareItems.each { multiFacetAwareItemDataBinding ->
Done

2021-12-02 16:32 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/UrlMappings.groovy
> +            group "/${multiFacetAwareItemDomainType}/${multiFacetAwareItemId}", {
This is actually a bit tricky because the FacetInterceptor assumes params.multiFacetAwareItemDomainType and params.multiFacetAwareItemId. So I've left it unchanged.

2021-12-03 12:27 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +            return notFound(params.multiFacetAwareItemClass, params.multiFacetAwareItemId)
sorry, can you split this so its a notFound if the model isnt found and a bad request if its not a model

2021-12-03 12:27 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +            return notFound(params.multiFacetAwareItemClass, params.multiFacetAwareItemId)
sorry, can you split this so its a notFound if the model isnt found and a bad request if its not a model

2021-12-03 13:06 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/UrlMappings.groovy
> +            group "/${multiFacetAwareItemDomainType}/${multiFacetAwareItemId}", {
we really need to make the URLs clear that its limited, the easiest way i would do is override ``` void facetResourceChecks() {
Utils.toUuid(params, 'id')
params.multiFacetAwareItemDomainType = params.multiFacetAwareItemDomainType?: params.catalogueItemDomainType ?: params.containerDomainType
params.multiFacetAwareItemId = params.multiFacetAwareItemId ?: params.catalogueItemId ?: params.containerId
checkAdditionalIds()
mapDomainTypeToClass(getOwningType(), true)
}``` 
and add elvis operators for modelDomainType and modelId in the 2 long lines.
there are other ways, such as implementing `checkAdditionalIds` and then overriding `getOwningClass` and `getOwningId` to return the super.xxx or if null return the modelXxx parm

2021-12-03 13:06 UTC, olliefreeman requested changes
See the updated comments on the unresolved issues

2021-12-06 09:15 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/UrlMappings.groovy
> +            group "/${multiFacetAwareItemDomainType}/${multiFacetAwareItemId}", {
Thanks for the tip, done.

2021-12-06 09:15 UTC, aaronforshaw commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +            return notFound(params.multiFacetAwareItemClass, params.multiFacetAwareItemId)
Done

2021-12-06 13:47 UTC, olliefreeman approved these changes

2021-12-06 13:49 UTC, merged