Feature/gh 182
MauroDataMapper/mdm-core pull request #200
Opened 2021-11-25 20:32 UTC by GBishop-PHSA

2021-11-25 20:36 UTC, GBishop-PHSA commented
This pull request is an initial attempt at fixing the Class Copy issue when a Class has metadata and at least one of its Elements has metadata. The metadata is not saved after the copy, and the validation fails for the parent catalogue item id.

Change to the BootstrapModels was to add metadata at the class and element level for the Class: 'parent'. This causes the test 'C01 : test copying (as writer to both DataModels)' in uk.ac.ox.softeng.maurodatamapper.testing.functional.datamodel.item.DataClassFunctionalSpec to fail with  the validation error.

2021-12-01 10:19 UTC, olliefreeman requested changes
So stepping through the copy->save

we do 
1. `uk.ac.ox.softeng.maurodatamapper.core.controller.CatalogueItemController#saveResource`
2. `uk.ac.ox.softeng.maurodatamapper.core.controller.CatalogueItemController#serviceInsertResource`
3. `uk.ac.ox.softeng.maurodatamapper.datamodel.item.DataClassController#serviceInsertResource`
4. `uk.ac.ox.softeng.maurodatamapper.datamodel.item.DataClassService#save(java.util.Map, uk.ac.ox.softeng.maurodatamapper.datamodel.item.DataClass)`

at this point deepSave == true and saveDataTypes == true.

we cant save DEs until its parent DC and its DT is saved, which is why the `saveDataClassHierarchy` removes all content from a DC and then we save the DTs and then the standard `uk.ac.ox.softeng.maurodatamapper.core.model.CatalogueItemService#save(java.util.Map, K)` method is called as this cascades the save to the DEs

The appropriate way to do this is to accept that this method already has custom saving in place so we should save the result of `super.save(args, domain)` and then do some post processing

```groovy
    @Override
    DataClass save(Map args, DataClass domain) {
        // If not previously saved then allow a deep save and/or datatype save
        Collection<DataTypes> newDataTypes
        if (!domain.ident()) {
            if (args.deepSave) {
                saveDataClassHierarchy(domain)
            }

            // If ignore datatypes then skip this bit or DC already been saved as this is designed to handle full builds or copies
            if (args.saveDataTypes) {
                newDataTypes = saveDataTypesUsedInDataClass(domain)
            }
        }

        DataClass saved = super.save(args, domain)
        if(args.deepSave){
            updateDataClassHierarchyAfterInsert(saved)
        }
        if(newDataTypes){
        newDataTypes.each{dt ->
            dataTypeService.updateFacetsAfterInsertingCatalogueItem(dt)
        }
        }
      saved
  }

    Collection<DataTypes> saveDataTypesUsedInDataClass(DataClass dataClass) {
    the last line of this is a saveAll which returns a list, so just need to update the method to return
}

void updateDataClassHierarchyAfterInsert(DataClass dataClass){
    if(dataClass.dataElements){
    dataClass.dataElements.each{de ->
    dataElementService.updateFacetsAfterInsertingCatalogueItem(de)
    }
    }
    
    if(dataClass.dataClasses){
    dataClass.dataClasses.each{dc ->
    updateDataClassHierarchyAfterInsert(dc)
    }
    
    }
}
```

hopefully this should help

2021-12-01 10:19 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +                                         multiFacetAwareItemId: el1.id,
if you look at the`uk.ac.ox.softeng.maurodatamapper.core.traits.domain.MultiFacetItemAware.setMultiFacetAwareItem` which is whats used during "map" constructors the id will be set when you set the MFAI, also the addToMetadata will set the MFAI as well, so the cleaner way is to create the metadata without those 2 fields, then addToMetadata then checkAndSave the MFAI then the MD

2021-12-01 10:19 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
> +
this is not right, it doesnt properly handle several issues and also will then be called on all DC saves which isnt appropriate.

2021-12-10 01:00 UTC, GBishop-PHSA commented
Ready for re-review. I've implemented the changes to the Bootstrap data setup and also to the DataClassService. I made an addition, where the DataElements are saved without validation before the Data Class save with validation is called.

2021-12-13 10:52 UTC, olliefreeman requested changes
All the ModelServices and ModelItemServices extend the CatalogueItemService which handles all the facet fixing as part of the save method. If you always make sure you use the relevant service method to save anything you should find that all issues are taken care of. 

Your fix here is to make sure the DCService handles addtl issues when DCs are saved. Thereby making the Service save method even more reliable

2021-12-13 10:52 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
> +        if(dataClass.dataElements){
if you call dataElementService.save() here it will do the save and the update of the facets all in one go as this method is the preferred way to save anything as it passes up to the catalogueItemService.save method

2021-12-13 10:52 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
> +            this.saveDataElements(domain)
not needed if you make the change in the updateDCHAfterInsert

2021-12-13 10:52 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
> +    void saveDataElements(DataClass dataClass) {
Can remove this whole method

2021-12-15 18:26 UTC, GBishop-PHSA commented
@olliefreeman I've removed the unneeded saveElements method and called the service save method. Ready for re-review.

2021-12-16 11:15 UTC, olliefreeman requested changes
There are a number of failing tests which need to be fixed, however i'm happy with the code

2021-12-20 12:31 UTC, olliefreeman approved these changes

2021-12-20 12:31 UTC, merged