Subscribed models newer versions
MauroDataMapper/mdm-core pull request #201
Opened 2021-11-26 09:00 UTC by joe-crawford

- Add newerVersions endpoint for published/subscribed models on local and remote catalogues
- Fix to version link importing for subscribed models and subscribed model security
- Extend federation client timeout

2021-11-26 09:05 UTC, joe-crawford commented
Have marked SubscribedModelFunctionalSpec test as ignore because these connect to the Continuous Deployment instance. However they can successfully from Jenkins.

Also N.B. `V2_3_0__cleanup_subscribedmodel_securableresourcegrouproles.sql` in mdm-security contains a reference to a table in mdm-plugin-federation.

2021-11-30 11:16 UTC, olliefreeman requested changes
Happy with the vast majority of this, looks good, just need to make a couple of changes.
* SQL migration needs to handle the federation not existing
* Configurable timeout on SC with a default of 5m not 30
* Sort ordering wrt ModelType

2021-11-30 11:16 UTC, olliefreeman commented on mdm-security/grails-app/conf/db/migration/security/V2_3_0__cleanup_subscribedmodel_securableresourcegrouproles.sql
> +      securable_resource_id NOT IN (SELECT id FROM federation.subscribed_model);
You need to make this work when the federation schema and this table does not exist, we cant guarantee that the security will run before federation or that the federation module hasnt been included

2021-11-30 11:16 UTC, olliefreeman commented on mdm-plugin-federation/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/federation/PublishedModel.groovy
> +@Sortable(includes = ['modelLabel', 'modelType', 'modelVersion'])
When we build the tree (which is the only place we really do ordering of multiple models) we dont really care about modelType. I feel that either we do modelType first in ordering or we remove it

2021-11-30 11:16 UTC, olliefreeman commented on mdm-plugin-federation/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/federation/web/FederationClient.groovy
> +        httpClientConfiguration.setReadTimeout(Duration.ofMinutes(30))
30mins for a live connection to a server is very very long, what you're saying here is hold at this point in the code for 30mins for a response, this could collapse the UI as the UI will wait for a response from us before renderering the tree. 
I think that its acceptable to make this a configurable option so that if a server is slow then the sys admins can up the timeout but 30mins should not be hardcoded.
I think the best option would be a configurable timeout for the SubscribedCatalogue so that each SC can be customised, and then a default timeout in the yaml files using grailsApplication.config.<> to acess it. The prop should be `maurodatamapper.federation.subscribedcatalogue.default.timeout: 5`

2021-12-02 14:30 UTC, joe-crawford commented on mdm-security/grails-app/conf/db/migration/security/V2_3_0__cleanup_subscribedmodel_securableresourcegrouproles.sql
> +      securable_resource_id NOT IN (SELECT id FROM federation.subscribed_model);
Have added a DO block with a check that the table exists.

2021-12-03 13:10 UTC, olliefreeman approved these changes

2021-12-03 13:12 UTC, merged