Feature/mc 9631 - Branch and merge Model Data Type
MauroDataMapper/mdm-core pull request #223
Opened 2021-12-22 10:59 UTC by aaronforshaw

- When branching a Versioned Folder, update Model Data Types in the branched folder so that they point to the branched model
- Update ModelDataType.diff so that it only returns a diff on modelResourceId and modelResourceDomainType if the paths of the pointed to resource in branch and target are different after ignoring differences in the branch and version

2021-12-22 11:43 UTC, olliefreeman requested changes
Looks like the methodology is right, 

All the stuff in path and path node and model, can you replace it all with the use of  `boolean matchesIdentifier(PathNode otherPathNode, String modelIdentifierOverride = null)` as thats why that method exists, you can pass in a branch name or model version number as the override and it will do everything you've coded up for you.

2021-12-22 11:43 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/ModelDataType.groovy
> +        GrailsApplication grailsApplication = Holders.getGrailsApplication()
i'd prefer it if we used a transient field `model` which we then populated inside one of the services with the models, rather than doing domain lookups inside a domain.
We have a similar transient field in the Facet class.
 Also you've loaded these models already in the DMS, so you can just push the loaded model into the transient field

2021-12-22 11:43 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/ModelDataType.groovy
> +                if (!thisResourcePath.equalsIgnoringModelIdentifier(otherResourcePath)) {
you can use matches() here

2021-12-22 11:43 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy
> +    void updateCopiedCrossModelLinks(K copiedModel, K originalModel, String branchName) {
Dont see why you need the branch name, you have the copied and original model which means you have the branch name as its the copiedModel.branchName field

2021-12-29 12:59 UTC, aaronforshaw commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy
> +    void updateCopiedCrossModelLinks(K copiedModel, K originalModel, String branchName) {
Done

2022-01-17 14:38 UTC, aaronforshaw commented on mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/ModelDataType.groovy
> +                if (!thisResourcePath.equalsIgnoringModelIdentifier(otherResourcePath)) {
Done

2022-01-17 14:42 UTC, aaronforshaw commented on mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/ModelDataType.groovy
> +        GrailsApplication grailsApplication = Holders.getGrailsApplication()
I have not done this. In the DMS the models are available in DataModelService.updateCopiedCrossModelLinks. This method is used on branching, whereas in ModelDataType the models are required when merging.

2022-01-17 14:52 UTC, aaronforshaw commented
@olliefreeman Please see updated description at the top of this PR.

2022-01-25 21:13 UTC, olliefreeman approved these changes
with the changes in commit im happy with this now

2022-01-25 23:35 UTC, olliefreeman commented
failing test is a known flaky test so merging

2022-01-25 23:35 UTC, merged