Feature/mc 9632
MauroDataMapper/mdm-core pull request #229
Opened 2022-01-06 20:59 UTC by aaronforshaw

tbc

2022-01-11 10:14 UTC, olliefreeman requested changes
Apart from the below i'm happy with this.

I disagree with the need for the CreatorAwareUtils:
 Diffs should not be detecting the change at the subdomain level. i.e. `domain.dataType.label` should not be a detected change of domain. It should be a detected change of dataType, the domain should not care that the dataType label has changed. If the datatype has changed then the id would be different, otherwise the "pointer" would remain the same and the diff would state that the datatype itself has been modified.
 
 Can you provide the exact situation this is happening and why its needed, for me to better understand

2022-01-11 10:14 UTC, olliefreeman commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/VersionedFolderService.groovy
> +        CreatorAwareUtils.patchCreatorAwareField(domain, fieldName, modificationPatch.sourceValue)
see the main review...this shouldnt be happening

2022-01-11 10:14 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy
> +        CreatorAwareUtils.patchCreatorAwareField(domain, fieldName, modificationPatch.sourceValue)
see main review

2022-01-11 10:20 UTC, aaronforshaw commented
> Apart from the below i'm happy with this.
> 
> I disagree with the need for the CreatorAwareUtils: Diffs should not be detecting the change at the subdomain level. i.e. `domain.dataType.label` should not be a detected change of domain. It should be a detected change of dataType, the domain should not care that the dataType label has changed. If the datatype has changed then the id would be different, otherwise the "pointer" would remain the same and the diff would state that the datatype itself has been modified.
> 
> Can you provide the exact situation this is happening and why its needed, for me to better understand

@olliefreeman At

https://github.com/MauroDataMapper/mdm-core/blob/e202601fc265d2a49ae0248310f312f16b929513/mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElement.groovy#L198-L205 

there is a string appended with dataType.label

Similarly in ReferenceDataElement (which is presumably copied from DataElement).

2022-01-14 10:09 UTC, olliefreeman commented
as discussed in the meeting, we need to change this to "path" for the datatype comparison not label, then use the same coding format being developed for the model datatypes

2022-02-01 09:19 UTC, aaronforshaw commented
Updated to use the pathing approach for referenceDataTypeLabel, and also changed the tests following the removal of isLegacy option on endpoints.
The test failures appear to be inconsistent and not related to this change.

2022-02-11 09:16 UTC, merged