MC-9710 Export Folders as JSON (no Models)
MauroDataMapper/mdm-core pull request #239
Opened 2022-02-02 21:21 UTC by adjl

Allow Folders (sans Models) to be exported as JSON.

* Implement the `exportFolder` controller action and corresponding endpoint
* Write functional tests to verify export of simple and nested Folders
* Write integration test and expected-output files to verify export of Folders with facets and child Folders
* Create `FolderJsonExporterService`
* Create `FolderExporterProviderService`
* Create generic `ContainerExporterProviderService` for abstraction/extension, e.g., for Classifiers

2022-02-03 00:17 UTC, adjl commented
Should I also add an export test to FolderInterceptorSpec?

2022-02-11 09:40 UTC, olliefreeman requested changes
Mostly good, just a few small changes needed, see the comments.

2022-02-11 09:40 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/ContainerExporterProviderService.groovy
> +    abstract String getNoIdFoundErrorCode()
The idea of error codes is that "we"(developers) can use search in the codebase to find the error code and jump straight to the place it failed without the stacktrace therefore i would just use the code `CIPS01` rather than bothering with a requirement for a custom code, that way its clear where it came from.

2022-02-11 09:40 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/ContainerExporterProviderService.groovy
> +        containerIds?.unique()?.each {
just use `containerService.getAll(containerIds)` this will make 1 call to the db and return a list which is actually a guaranteed set as it uses the "where id in ()" sql query

2022-02-11 09:40 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        exportResource([exportModel: exportModel], format, exportViewPath)
So ExportModel is not a thing for exporting models only, its a "model" for exporting anyting where we have a thing we're exporting and metadata we attach to this. therefore we dont need the ExportFolder class, and you can just pass the exportFolder map used here into the ExportModel class, therefore the changes here, and to ExportModel are not needed

2022-02-11 09:40 UTC, olliefreeman commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/FolderJsonExporterService.groovy
> +        exportFolder(new ExportFolder(folder, exportMetadata), fileType)
just call exportModel and pass a new ExportModel class

2022-02-11 09:40 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/ExportModel.groovy
> +class ExportModel implements ExportResource {
I would change all `CI model` to `MdmDomain mdmDomain` to make it cleaner and to allow you to use Folders in here

2022-03-03 18:47 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/ContainerExporterProviderService.groovy
> +    abstract String getNoIdFoundErrorCode()
Done

2022-03-03 18:47 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/ContainerExporterProviderService.groovy
> +        containerIds?.unique()?.each {
Done

2022-03-03 18:47 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        exportResource([exportModel: exportModel], format, exportViewPath)
Done

2022-03-03 18:47 UTC, adjl commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/FolderJsonExporterService.groovy
> +        exportFolder(new ExportFolder(folder, exportMetadata), fileType)
Done

2022-03-03 18:47 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/ExportModel.groovy
> +class ExportModel implements ExportResource {
Done

2022-03-03 18:55 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/ContainerExporterProviderService.groovy
> +    abstract String getNoIdFoundErrorCode()
Done

2022-03-03 18:55 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/ContainerExporterProviderService.groovy
> +        containerIds?.unique()?.each {
Done

2022-03-03 18:55 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        exportResource([exportModel: exportModel], format, exportViewPath)
Done

2022-03-03 18:55 UTC, adjl commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/provider/exporter/FolderJsonExporterService.groovy
> +        exportFolder(new ExportFolder(folder, exportMetadata), fileType)
Done

2022-03-03 18:55 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/ExportModel.groovy
> +class ExportModel implements ExportResource {
Done

2022-03-04 11:50 UTC, olliefreeman requested changes
All issues fixed, just 2 new ones..

`def` is technically bad as we should type to a class, however its not evil and i actually prefer `def` over `Object`. we certainly shouldnt be replacing def with Object

2022-03-04 11:50 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        Object sw = new StringWriter()
If removing `def` please use the correct class not `Object`. I'm happy with def over Object for variable class types, but not when we know for a fact what it is..in this case a StringWriter

2022-03-04 11:50 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        Object writable = template.make(exportModel: exportModel)
If replacing `def` this would be `Writable`

2022-03-04 11:50 UTC, olliefreeman commented on mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/provider/MauroDataMapperServiceProviderFunctionalSpec.groovy
> +    "name": "FolderJsonExporterService",
thats a good question, it should appear in both and in all plugins extending core

2022-03-07 09:55 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        Object sw = new StringWriter()
Done

2022-03-07 09:55 UTC, adjl commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/TemplateBasedExporter.groovy
> +        Object writable = template.make(exportModel: exportModel)
Done

2022-03-21 16:00 UTC, olliefreeman commented
@adjl you need to run `gradle licenseFormat` to add the missing headers to the new files ... run it and commit it with the commit message `add missing headers`

2022-03-21 16:11 UTC, olliefreeman commented
you also need to add `@Slf4j` to `MauroDataMapperServiceProviderFunctionalSpec` which will reveal the failing `'test get exporters'` message and the expected json.

ANY `MauroDataMapperServiceProviderFunctionalSpec` will need the folder exporter added to the list of expected json, and in mc-9714 the importer will need to be added

2022-03-21 16:11 UTC, olliefreeman commented on mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/provider/MauroDataMapperServiceProviderFunctionalSpec.groovy
> +    "name": "FolderJsonExporterService",
it does... see the comment later on

2022-03-28 11:03 UTC, merged