Feature/gh 241
MauroDataMapper/mdm-core pull request #280
Opened 2022-02-28 08:13 UTC by joe-crawford

2022-03-17 09:38 UTC, olliefreeman requested changes
Only 1 issue that needs fixing

2022-03-17 09:38 UTC, olliefreeman commented on mdm-plugin-terminology/grails-app/services/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermService.groovy
> +    Term copyTerm(CodeSet copiedCodeSet, Term original, User copier, UserSecurityPolicyManager userSecurityPolicyManager,
so close to not having any comments....

we never copy terms when we copy a codeset as terms are owned by a terminology, when copying a codeset we always use the existing term and just add the existing term to the copied codeset, therefore this method needs to be removed

2022-03-28 08:33 UTC, joe-crawford commented
Failing test looks to be unrelated

2022-03-28 08:35 UTC, joe-crawford commented on mdm-plugin-terminology/grails-app/services/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermService.groovy
> +    Term copyTerm(CodeSet copiedCodeSet, Term original, User copier, UserSecurityPolicyManager userSecurityPolicyManager,
Have removed.

2022-03-28 10:59 UTC, merged