Profile datatype fixes and restrict dynamic profile endpoints to finalised versions
MauroDataMapper/mdm-core pull request #293
Opened 2022-03-15 16:22 UTC by joe-crawford

- Treat custom datatypes in profiles as strings (resolves #213)
- Fix to loading date formats from ApiProperties (resolves #290)
- Use finalised dynamic profile as default version (resolves #292), restrict dynamic profiles to finalised only in profile providers endpoint, sort profile provider endpoints

2022-03-15 16:28 UTC, joe-crawford commented
Failing branch test looks like a timing issue.

PR includes PR #287.

2022-03-17 09:56 UTC, olliefreeman requested changes
wrt 290 and the not set fields... wow how did i miss that one! bug fail on me

ProfileService -> in 99% of situations where we call any method with the param finalisedOnly we're passing "true" therefore really the default to this param should now be true and the 1 location where we seem to asking for "false" (ProfileController nonProfileMetadata) should be where we pass a param of false...this is a much cleaner approach

2022-03-17 09:56 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        respond profileProviderServices: profileService.getAllProfileProviderServices(true).sort()
it would be much cleaner for all these service methods to actually perform the cleaning rather than the controller asking for it, this makes sure that whoever calls the methods always gets the data in the format we would prefer...which in this situation is sorted...this comment applies to all changes in this file

2022-03-17 09:58 UTC, olliefreeman commented
Note to self....need #287 merged first unless this branch is rebased off `feature/gh-277` and onto `develop`

2022-03-25 10:29 UTC, joe-crawford commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        respond profileProviderServices: profileService.getAllProfileProviderServices(true).sort()
Have changed the ProfileService methods to sort by version, and (for dynamic profiles) to restrict to finalised profile versions by default (via change in underlying `getAllProfileProviderServices` service method).

2022-03-25 10:31 UTC, joe-crawford commented
PR has been rebased onto #287 and includes change from review of that PR.

2022-03-28 10:33 UTC, olliefreeman approved these changes
Im happy with this.

As a word of note (and it doesnt matter for this case, but will for larger domains) using the "only validate these fields" in the  Validateable class is dangerous for larger domains. The reason is that it infact validates the entire domain and then removes all field errors which dont match the requested fields. 
Therefore in this case its fine as the domain is small and its not doing any complicated validation, but beware in larger domains with more complex valdiation as its will cascade the validation .

2022-03-28 10:48 UTC, merged