Add export URLs and content types to published models endpoints and Atom feed
MauroDataMapper/mdm-core pull request #304
Opened 2022-04-27 14:45 UTC by joe-crawford

Changes for the 'publish' side of federation using MIME content types (part of mc-9618):

- Add XML versions of Mauro published model endpoints
- Add XSDs (in mdm-plugin-federation/grails-app/assets/xsd) for Atom published model feed, and Mauro published model XML endpoints and validate in tests.
- Add exporter links and content type to published model and Atom responses (mc-9831, mc-9832)
- Add content type string to ExporterProviderServices (part of mc-9835)

2022-05-03 09:56 UTC, olliefreeman commented
dont worry about retrying this, the tests all passed, it got stuck on the SCA so i stopped the job

2022-05-03 15:12 UTC, olliefreeman requested changes
A few small changes, otherwise looks good

2022-05-04 08:41 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/exporter/ExporterProviderService.groovy
> +    boolean getIsPreferred() {
Have removed. Intention was to separate out the native exporters so they would always be rendered first as Atom doesn't support any other way of indicating which link is preferred. I've set the order of the JSON exporters to HIGHEST_PRECEDENCE and the XML exporters to HIGHEST_PRECEDENCE+1.

2022-05-04 08:42 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/publish/PublishService.groovy
> +                model.finalised && model.authority.id == authorityService.getDefaultAuthority().id
Resolved

2022-05-04 08:42 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/publish/PublishService.groovy
> +                new Link(MdmAtomPublishedModelRenderer.RELATIONSHIP_ALTERNATE,
Resolved

2022-05-04 08:42 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueService.groovy
> +                if (pm.links) links = pm.links.collect {link -> new Link(MdmAtomPublishedModelRenderer.RELATIONSHIP_ALTERNATE, link.url).tap {contentType = link.contentType}}
Resolved

2022-05-06 14:58 UTC, olliefreeman commented
test failures not due to this PR

2022-05-06 14:58 UTC, merged