Feature/mc 9833
MauroDataMapper/mdm-core pull request #309
Opened 2022-05-23 21:53 UTC by joe-crawford

2022-05-24 08:32 UTC, joe-crawford commented
Failing test on branch and PR builds is not related.

2022-05-24 08:46 UTC, joe-crawford commented
Compatibility note:

- The changes are backwards incompatible for subscription to and from older versions of Mauro as subscribed catalogues (i.e. the new 'Mauro JSON' subscribed catalogue type is not compatible with the previous subscribed catalogues). The migration script does migrate previous subscribed catalogues if both remote and local instances are updated.
- The changes to the content type fields in ExporterProviderService are backwards incompatible.

Notes on changes:
- In SubscribedModelService, `federateSubscribedModel` supports federating an MdmDomain if certain properties are found dynamically. The intention is to allow federating a Model or a VersionedFolder, in particular so importers for FHIR JSON multi-item types (FHIR packages/bundles) can import a VersionedFolder and a 1:1 link between SubscribedModels and imported domains is maintained.
-  SubscribedModelFunctionalSpec tests check that this PR is present on the CD instance before running (by checking for SC `/types` endpoint).
- Re: mc-9835 - grails.mime.types definitions not used as these affect client-side content type negotiation. URLs are imported as byte arrays and passed to importers.

2022-05-25 12:25 UTC, joe-crawford commented
Failing PR test unrelated again.

2022-06-09 09:39 UTC, olliefreeman requested changes
I would suggest adding a `public static final CONTENT_TYPE = ''` to each exporter service, and then having the getContentType() method returning this variable, then in the importer services you have the handlesContentType check against that variable, that way if we want to change the content type we only have to do it in 1 place and it applies across all things that use it. It also means if we have a importer which handles multiple types they can check a list of psf variables 

See the other comments and questions

2022-06-09 09:39 UTC, olliefreeman commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/provider/importer/XmlImportMapping.groovy
> +    Map<String, Object> convertToMap(NodeChild nodes, List<String> exclude = ['id']) {
where are we excluding anything other than id??

2022-06-09 09:39 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/federation/converter/SubscribedCatalogueConverter.groovy
> +interface SubscribedCatalogueConverter {
can we use traits not j17 interfaces please

2022-06-09 09:39 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelService.groovy
> +    List<MdmDomainService> domainServices
i would keep this at modelServices, as we're not going to federate and subscribe to anything other than models, which means youre just making more processing calculations as you have to search more objects to find a match

2022-06-09 09:39 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelController.groovy
> +    def federate(SubscribedModelFederationParams subscribedModelFederationParams) {
if you're going to use command objects which are validatable then you should call validate on the object before you do anything else and then if the object is invalid you can respond with the objects errors field. this will ensure thate the SM instance is there and that everythign you want/need is provided
```groovy
if (subscribedModelFederationParams.hasErrors() || !subscribedModelFederationParams.validate()) {
transactionStatus.setRollbackOnly()
respond subscribedModelFederationParams.errors // STATUS CODE 422
return 
}
```

2022-06-09 09:39 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModel.groovy
> +        subscribedModelType nullable: true
even with nullable:true you should leave blank:false in .. blank is a check against an empty string which we never want

2022-06-09 09:39 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModel.groovy
> +    String subscribedModelId
Why are we not storing this as a UUID??

2022-06-09 09:59 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/provider/importer/XmlImportMapping.groovy
> +    Map<String, Object> convertToMap(NodeChild nodes, List<String> exclude = ['id']) {
This was part of an attempt to use convertToMap with Atom XML, where I wanted to include `id` elems, however not used because of data in XML attributes. I can revert this.

2022-06-09 10:00 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/federation/converter/SubscribedCatalogueConverter.groovy
> +interface SubscribedCatalogueConverter {
Will change.

2022-06-09 10:05 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelController.groovy
> +    def federate(SubscribedModelFederationParams subscribedModelFederationParams) {
Will change.

2022-06-09 10:05 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModel.groovy
> +        subscribedModelType nullable: true
Will change.

2022-06-09 10:07 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModel.groovy
> +    String subscribedModelId
This is because the `subscribedModelId` is now taken from the ID field from a Mauro JSON catalogue (UUID) or the `id` from an Atom feed, which might not be a UUID.

2022-06-09 10:08 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueService.groovy
> +            if (!subscribedAuthority.label || publishedModels == null) {
Are we sure we want to reject the empty list as this will prevent subscribing to valid catalogues which haven't yet published models?

2022-06-09 17:39 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelService.groovy
> +    List<MdmDomainService> domainServices
okay ... in that case leave as MdmDomainService list

2022-06-09 17:41 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueService.groovy
> +            if (!subscribedAuthority.label || publishedModels == null) {
okay ... then use == null, however i would advise making a documented note/comment in the code that if that method returns null then it is invalid but it is allowed to return an empty list and be valid...with that justification...that way people will know why we're not using the standard groovy check

2022-06-10 11:53 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/provider/importer/XmlImportMapping.groovy
> +    Map<String, Object> convertToMap(NodeChild nodes, List<String> exclude = ['id']) {
Reverted

2022-06-10 11:53 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/federation/converter/SubscribedCatalogueConverter.groovy
> +interface SubscribedCatalogueConverter {
Changed to trait

2022-06-10 11:54 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelController.groovy
> +    def federate(SubscribedModelFederationParams subscribedModelFederationParams) {
Added the validation snippet, thanks.

2022-06-10 11:54 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModel.groovy
> +        subscribedModelType nullable: true
Changed

2022-06-10 11:55 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueService.groovy
> +            if (!subscribedAuthority.label || publishedModels == null) {
Added comment

2022-06-10 12:57 UTC, olliefreeman reviewed
just the one question about the validation

2022-06-10 12:57 UTC, olliefreeman commented on mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelController.groovy
> +        if (subscribedModelFederationParams.importerProviderService &&
shouldnt need to do this, the validation should cascade?

2022-06-10 13:16 UTC, joe-crawford commented on mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelController.groovy
> +        if (subscribedModelFederationParams.importerProviderService &&
It actually doesn't seem to cascade to the nested command object. It does to the domain object as expected though. I did try adding a custom validator in the SubscribedModelFederationParams to call the nested validate method which works but would require more handling to push the errors back up than the separate call.

Found this which seems to imply it's expected: https://plugins.grails.org/plugin/ctoestreich/cascade-validation (but surprising).

2022-06-13 08:14 UTC, merged