gh-256 use the securableResourceId
MauroDataMapper/mdm-core pull request #337
Opened 2022-07-13 12:56 UTC by aaronforshaw

Closes #256 

Fall back to using `securableResourceId` and add a test for the endpoint `GET /{securableResourceDomainType}/{securableResourceId}/groupRoles/{groupRoleId}/userGroups`

2022-07-19 10:30 UTC, joe-crawford commented
Thanks for this @aaronforshaw, I've got one comment.

2022-07-19 13:32 UTC, joe-crawford requested changes
Thanks @aaronforshaw, I've added one comment.

2022-07-19 13:32 UTC, joe-crawford commented on mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/UserGroupInterceptor.groovy
>      }
I think this could be a bit confusing as normally the `getId` method should return the ID of the type corresponding to the Controller and `getSecuredClass` method, so UserGroup in this case.

Would you be able to change this to the below? The tests should pass with:

```groovy
@Override
UUID getId() {
    params.userGroupId ?: params.id //?: params.securableResourceId
}

boolean before() {
    checkIds() // instead of securableResourceChecks()
    if (isIndex()) {
```

2022-07-21 11:30 UTC, aaronforshaw commented on mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/UserGroupInterceptor.groovy
>      }
This didn't quite work as some other tests failed.

But I realised I could revert the change to `UUID getUUID()`and instead override `UUID getSecuredId()`.

I think the test failures on Jenkins are down to Jenkins, as I have run them locally and they pass.

2022-07-21 12:06 UTC, joe-crawford commented on mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/UserGroupInterceptor.groovy
>      }
Thanks @aaronforshaw, good to clarify to reduce the chance of accidentally checking the wrong object's permissions if adding future endpoints.

2022-07-21 12:07 UTC, joe-crawford approved these changes

2022-07-21 12:07 UTC, merged