gh-363 request param to select finalized models by label
MauroDataMapper/mdm-core pull request #364
Opened 2022-09-28 00:10 UTC by GBishop-PHSA

gh-363 Provide a path in the API to view the latest finalised datamodel

eg. http://localhost:8080/api/dataModels/path/dm:DM_LABEL?finalised=true

2022-10-03 22:40 UTC, joe-crawford commented
@GBishop-PHSA, thanks, this looks like a good solution, however there's some errors in the tests relating to the path endpoints for folders. I think this may need some more handling for Versioned Folders (which should work like DataModels).

https://jenkins.cs.ox.ac.uk/job/Mauro%20Data%20Mapper/job/mdm-core/job/PR-364/1/display/redirect

2022-10-03 23:12 UTC, joe-crawford requested changes

2022-10-03 23:12 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/path/PathController.groovy
>              pathedResource = pathService.findResourceByPathFromRootResource(resource as MdmDomain, params.path)
Does this method `pathService.findResourceByPathFromRootResource` also need changing as it looks like a similar route into looking up a domain by its path?

2022-10-14 21:10 UTC, GBishop-PHSA commented
@joe-crawford I'm having an issue getting the tests to fail locally so I'm not sure how to investigate the failures

./gradlew -Dgradle.functionalTest=true :mdm-core:integrationTest
3 failed tests in AsyncJobFunctionalSpec

./gradlew -Dgradle.functionalTest=true :mdm-plugin-datamodel:integrationTest
1 failed test in DataModelFunctionalSpec

2022-10-17 12:46 UTC, joe-crawford commented
Thanks @GBishop-PHSA, this looks good and I'll merge it. I've made some minor tweaks in a branch `feature/gh-363` on this repo, could you pull those to your branch then I'll merge the PR?
- Auto reformat using the IntelliJ code style XML file
- Add extra abstract method without the params arg

The test failures originally were all HibernateOptimisticLockingFailureException or StaleStateException, basically these are sometimes expected failures of the Hibernate optimistic locking strategy that in actual use would need to be retried. They're related to a performance/reliability trade off of Hibernate, if they occurred more often in actual use it would be a problem but usually these happen just on the test server. They've passed after rerunning Jenkins.

2022-10-17 16:43 UTC, GBishop-PHSA commented
@joe-crawford, Thanks for looking at this. I've pulled in your changes and squashed the commits.

2022-10-18 08:28 UTC, joe-crawford commented
@GBishop-PHSA, Great, thank you!

2022-10-18 08:28 UTC, joe-crawford approved these changes

2022-10-18 08:29 UTC, merged