postgresql to aurora db migration fix
MauroDataMapper/mdm-core pull request #392
Opened 2023-02-06 15:55 UTC by oleksiiRybak

2023-02-06 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MauroDataMapper/mdm-core?pullRequest=392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MauroDataMapper/mdm-core?pullRequest=392) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MauroDataMapper/mdm-core?pullRequest=392) it.</sub>

2023-02-06 21:22 UTC, joe-crawford requested changes
I think there are a few issues, could you have a look at the below?

* The triggers are used to enforce the constraints (foreign keys etc.) in the DB so it can definitely cause a problem deleting without them, I've tried on a test DB and got:
```
DELETE FROM core.breadcrumb_tree
[2023-02-06 21:19:04] [23503] ERROR: update or delete on table "breadcrumb_tree" violates foreign key constraint "fksiu83nftgdvb7kdvaik9fghsj" on table "data_type"
[2023-02-06 21:19:04] Detail: Key (id)=(8f7aed00-1a0d-4f47-9c9b-3b4230a5ad6e) is still referenced from table "data_type".
```
* Deleting the schema entry will mean it runs again on already migrated DBs which isn't ideal as BreadcrumbTrees have been a sensitive area in the past, it would be best to update the checksum by using the flyway CLI (`flyway repair`) to get the updated checksum for the file.
* Looks like a typo in the version number (5.1.3)

2023-02-07 16:56 UTC, joe-crawford commented
Thanks @oleksiiRybak, I haven't tested this myself yet but I have some comments.

2023-02-07 17:04 UTC, joe-crawford commented
If you do need a solution for Aurora and Postgres DBs with existing data in the future, I think what should work is using the information tables to look up the names of the constraints from foreign keys etc., and then use dynamic (pgpl)SQL to disable/enable them by name, which should avoid the superuser issue.

2023-02-08 14:14 UTC, oleksiiRybak commented
@joe-crawford I've done some further changes, please review them...

2023-02-08 17:04 UTC, joe-crawford requested changes
Using session_replication_role looks good if that works on Aurora too.

However the migration will fail on existing Postgres DBs due to the index already being created, could you change the DELETE flyway entry to UPDATE with the checksum?

Could you also have a look at the formatting comment.

Thanks :+1:

2023-02-08 17:04 UTC, joe-crawford commented on mdm-core/grails-app/conf/db/migration/core/V5_1_3__delete_invalid_breadcrumb_trees.sql
> +$$;
This looks good to me and I have tested this on Postgres.

2023-02-09 10:14 UTC, agreenhalgh commented on mdm-core/grails-app/conf/db/migration/core/V5_1_3__delete_invalid_breadcrumb_trees.sql
> +						ON c.parent_id = v.id
@oleksiiRybak can we set up some linting for this in the pipeline?

2023-02-09 10:17 UTC, oleksiiRybak commented on mdm-core/grails-app/conf/db/migration/core/V5_1_3__delete_invalid_breadcrumb_trees.sql
> +						ON c.parent_id = v.id
thanks, done

2023-02-09 10:45 UTC, awilkins commented on mdm-core/grails-app/conf/db/migration/core/V5_1_3__delete_invalid_breadcrumb_trees.sql
> +						ON c.parent_id = v.id
Maybe add an EditorConfig file to the tree as well, perhaps

```ini
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

2023-02-09 10:59 UTC, joe-crawford commented on mdm-core/grails-app/conf/db/migration/core/V5_1_3__delete_invalid_breadcrumb_trees.sql
> +						ON c.parent_id = v.id
Thanks @awilkins, FYI there are IntelliJ code style and EditorConfig files at https://github.com/MauroDataMapper/mdm-core/tree/develop/gradle

2023-02-09 11:11 UTC, oleksiiRybak commented on mdm-core/grails-app/conf/db/migration/core/beforeValidate.sql
> +      description = 'delete invalid breadcrumb trees';
@joe-crawford  I've added an additional protection in case we run create index in a db which already has it and similarly with the temporary valid_breadcrumb_trees_temp so it shouldn't cause any problems so I think it is OK to go with delete in this case.

2023-02-09 11:29 UTC, joe-crawford commented on mdm-core/grails-app/conf/db/migration/core/beforeValidate.sql
> +      description = 'delete invalid breadcrumb trees';
I think it should still be `UPDATE` as rerunning the migrations in general isn't really safe, and if it fails it stops the system from starting. In this case it will still cause problems on existing Postgres DBs because the temporary table is dropped per session so it will still try to insert rows.

2023-02-09 12:03 UTC, oleksiiRybak commented on mdm-core/grails-app/conf/db/migration/core/beforeValidate.sql
> +      description = 'delete invalid breadcrumb trees';
ok, I will look into that. thanks

2023-02-09 12:08 UTC, joe-crawford commented on mdm-core/grails-app/conf/db/migration/core/beforeValidate.sql
> +      description = 'delete invalid breadcrumb trees';
From memory you have to install the flyway CLI, run `flyway repair` and then that updates the value in the flyway_schema_migration table with the new checksum.

2023-02-09 12:13 UTC, oleksiiRybak commented on mdm-core/grails-app/conf/db/migration/core/beforeValidate.sql
> +      description = 'delete invalid breadcrumb trees';
thank you, looking into that...

2023-02-09 16:49 UTC, joe-crawford commented
Great, this looks good to me.

Have tested on a Postgres instance with existing data and a new blank Postgres database, both successful.

2023-02-09 16:49 UTC, joe-crawford approved these changes

2023-02-09 16:49 UTC, merged