gh-394: Save Theme images in the database
MauroDataMapper/mdm-core pull request #403
Opened 2023-03-15 14:59 UTC by NigelPalmer

This is the backend work required to allow Theme Images to be uploaded. See gh-394.

2023-03-15 17:49 UTC, pjmonks requested changes
There are a lot of changes here, especially having to make deep changes to existing functionality, good effort.

I've given some cursory feedback but I think someone like @joe-crawford , who has more experience, should give a more detailed review.

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            resource = themeImageFileService.findByApiPropertyId(params.apiPropertyId)
For consistency sake, I'm not sure why the line above uses `Utils.toUuid()` yet this line ignores the hard conversion and uses type inference. Maybe this is typical in this codebase, but I would have thought either infer both or cast both instead.

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            return
Should this line say `return notFound(params.is)` instead? At the moment, it seems the `return` is `void` whereas other conditions return a proper response.

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (params.apiPropertyId && themeImageFileService.apiPropertyHasImage(Utils.toUuid(params.apiPropertyId)))
Does `ThemeImageFileService` need both an `apiPropertyHasImage()` and `findByApiPropertyId()` method? I believe `apiPropertyHasImage()` calls `findByApiPropertyId()` and checks for null, so it's shorthand. I'm not too familiar with the coding styles/conventions in `mdm-core`, so my opinion is only subjective.

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (params.containsKey('apiPropertyId')) {
What is the difference between this line and `if (params.apiPropertyId)`? Another inconsistency I see, but don't have enough Groovy knowledge to know if there is an actual difference.

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
> +    private static final Pattern PRECUSOR = ~/^data:image\/[^;]*;base64,?/
Typo - seems like it should be `PRECURSOR`

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
> +class ImageFile implements CatalogueFile, MdmDomain {
Looks like good use of inheritance for these image types

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileService.groovy
> +    List<ThemeImageFile> listWithPagination(Map pagination = [:]) {
`listWithPagination()` and `list()` look identical to me, is there a reason for both to exist?

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileService.groovy
> +        if (!apiProperty.value.matches("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")) return null
This check to see if a string represents a UUID feels like a utility function to me, either to create one or check one already exists. Then stating `if (!isUuid(apiProperty.value))` will read a lot clearer.

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
> +            String error = e.message;
I'm not sure what this `catch` block is trying to achieve, the `String error` has no usage after this line. Perhaps this is some testing code left over?

2023-03-15 17:49 UTC, pjmonks commented on mdm-core/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileServiceSpec.groovy
> +        ThemeImageFile findByApiPropertyId(UUID apiPropertyId)
Should these comments be here?

2023-03-15 17:49 UTC, pjmonks commented on mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/UrlMappings.groovy
> +                '/image'(single: 'themeImageFile', excludes: DEFAULT_EXCLUDES)
I'm a bit confused why this mapping for theme image files exists in `mdm-security`, especially as I can't see any controllers/interceptors in this plugin for it (again, might be my lack of Grails knowledge though). What does this endpoint do?

2023-03-15 17:49 UTC, pjmonks commented on mdm-testing-functional/build.gradle
> +        runtimeOnly 'uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-explorer:1.0.0-SNAPSHOT'
This looks like it was included for testing, it should probably be removed before merging.

2023-03-16 11:27 UTC, joe-crawford commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileService.groovy
> +        if (!apiProperty.value.matches("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")) return null
I think you can do !Utils.toUuid(...) to check if it's a UUID.

2023-03-16 11:50 UTC, NigelPalmer commented on mdm-core/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileServiceSpec.groovy
> +        ThemeImageFile findByApiPropertyId(UUID apiPropertyId)
No. Removed.

2023-03-16 11:57 UTC, NigelPalmer commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
> +            String error = e.message;
Yes, this is debug code that should have been removed. Reverted the method to it's previous state.

2023-03-16 12:02 UTC, NigelPalmer commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileService.groovy
> +        if (!apiProperty.value.matches("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")) return null
Updated to use Utils.toUuid.

2023-03-16 12:03 UTC, NigelPalmer commented on mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
> +    private static final Pattern PRECUSOR = ~/^data:image\/[^;]*;base64,?/
Typo inherited from original implementation. Now fixed.

2023-03-16 12:19 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            resource = themeImageFileService.findByApiPropertyId(params.apiPropertyId)
Fixed to use toUuid.

2023-03-16 13:54 UTC, NigelPalmer commented on mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
> +class ImageFile implements CatalogueFile, MdmDomain {
Thank you. :-)

2023-03-16 14:13 UTC, NigelPalmer commented on mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/UrlMappings.groovy
> +                '/image'(single: 'themeImageFile', excludes: DEFAULT_EXCLUDES)
I've removed this.

2023-03-16 14:30 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (params.containsKey('apiPropertyId')) {
`if (params.apiPropertyId)` will return false if the `apiPropertyId` key is present in the map but it has a value of `null` or if the key is not present at all. `params.containsKey('apiPropertyId')` will return true when the key is present in the map, but has a `null` value. In this case, when the `apiPropertyId` param is supplied, then we want to try and use it, even if it is null. We don't want to ignore it and try and use `id` instead. So it is correct to be used here. I have changed another `containsKey` reference though that is less relevant.

2023-03-16 14:30 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            return
Fixed to return a proper response and the correct id!

2023-03-16 14:31 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (params.apiPropertyId && themeImageFileService.apiPropertyHasImage(Utils.toUuid(params.apiPropertyId)))
Removed ThemeImageFileService and rejigged some logic that was using it to work without it.

2023-03-16 16:19 UTC, joe-crawford commented
Thanks for this @NigelPalmer, looks good! As there's quite a few changes I'm still having a look but have an additional comment:

* When I tried to upload an SVG image through the API property endpoint, it stored it fine, but when I tried to retrieve it, the content-type header was wrong which meant the browser couldn't display it. I think it should be possibly to allow SVGs by adding to `getContentType` in `CatalogueFile.groovy`.

2023-03-17 18:29 UTC, NigelPalmer commented on mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileService.groovy
> +    List<ThemeImageFile> listWithPagination(Map pagination = [:]) {
One has a default, one doesn't. I spoke to Joe and he said it was safe to add the default to the list function, so I have done that and deleted liwtWithPagination.

2023-03-17 18:30 UTC, NigelPalmer commented on mdm-testing-functional/build.gradle
> +        runtimeOnly 'uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-explorer:1.0.0-SNAPSHOT'
Already removed to get tests to run successfully.

2023-03-17 18:31 UTC, NigelPalmer commented
svg files now displayed correctly. This also required changes to the mdm-ui to get this to work properly.

2023-03-20 10:35 UTC, joe-crawford requested changes

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            resource = themeImageFileService.findByApiPropertyId(params.apiPropertyId)
I think that ideally if the API property itself doesn't exist, that should return an appropriate error message, I think you should be able to use a call to notFound(ApiProperty, params.apiPropertyId) to return in that case.

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            return
As above, I think this could be `return notFound(ApiProperty, params.apiPropertyId)`.

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    }
Is this possibly from debugging?

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            return
Ditto about the notFound being on the apiPropertyId

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileInterceptor.groovy
> +        }
It looks like there is no security on the update of the image using the `apiPropertyId` because of this, which could lead to a free for all! ;)

I think this should check for admin rights for everything except the show action.

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
> +
Could this possibly be an abstract class? Just to prevent any accidental attempts in the future to try and save a plain ImageFile to the database. Also I think I would remove the pathPrefix here as only the concrete objects should be pathable.

2023-03-20 10:35 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileInterceptor.groovy
> +        }
Actually to be consistent with other endpoints, everything under the `/admin` mapping should be admin-only, and the non-admin `show` mapping should set an `openAccess = true` param so it can be checked in the interceptor. An example is `ApiPropertyInterceptor.groovy`.

2023-03-20 10:51 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            resource = themeImageFileService.findByApiPropertyId(params.apiPropertyId)
I can see this was updated, but I think the `ApiProperty` arg should be included to get the correct class name in the error message.

2023-03-20 10:51 UTC, joe-crawford commented on mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
> +
This method can return `null` to disable pathing if it's required.

2023-03-20 11:39 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (saveResult && saveResult.Id && params.apiPropertyId) {
Looks like a type on the .Id property

2023-03-20 11:39 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (saveResult && saveResult.Id && params.apiPropertyId) {
Ditto about .Id

2023-03-20 11:53 UTC, joe-crawford commented on mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/file/ThemeImageFileControllerSpec.groovy
> +                apiProperty.lastUpdatedBy = updatedBy
This test seems to be passing locally but is failing on Jenkins, the issue is that `lastUpdatedBy` should be an email address rather than a user object, I think `.lastUpdatedBy = updatedBy.emailAddress` should fix it.

2023-03-20 14:32 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
>      }
@NigelPalmer, sorry, after our discussion last week I said I thought that this was fine to override the EditLoggingController, however looking at this with a fresh pair of eyes I have realised that there are some issues.

There are issues with the Grails framework if the response is set (which happens in the updateResponse/deleteResponse methods), and then a value is returned in the controller action method. I think the returned value triggers some additional response processing which fails as a response has already been sent. If I delete an image then hit the `DELETE` endpoint again, I get the following error response and stack trace:

```
{
    "status": 500,
    "reason": "Internal Server Error",
    "errorCode": "UEX--",
    "message": "JS-- - Unknown error",
    "path": "/error",
    "environment": "DEVELOPMENT",
    "version": "5.4.0-SNAPSHOT"
}
```

```
Mar 20, 2023 2:24:14 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'delete' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'delete' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1384)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1149)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:702)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.<============-> 99% EXECUTING [8m 37s]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilte
```

I imagine it might be possible to trigger a similar error with the update change as well, it might take multiple calls to get the stacktrace to show however. Due to the return issue it could affect other classes that use the method.

I think the best solution here is actually just to override the update() and delete() methods in the ThemeImageFileController, then you can do the updates within that when needed. ApiPropertyController and SubscribedCatalogueController are examples where it's already overridden.

2023-03-20 14:42 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    private void saveApiProperty(String apiPropertyId, String value = null) {
Not very important but I think when this is called the values are originally always UUIDs?

2023-03-20 14:51 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> + * Copyright 2020-2023 University of Oxford and Health and Social Care Information Centre, also known as NHS Digital
Some of the files need the licence changing to `NHS England` to get Jenkins to pass:

`[2023-03-20T10:57:39.816Z] Missing header in: mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
[2023-03-20T10:57:39.816Z] Missing header in: mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileInterceptor.groovy
[2023-03-20T10:57:39.816Z] Missing header in: mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileService.groovy
[2023-03-20T10:57:39.816Z] Missing header in: mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ImageFile.groovy
[2023-03-20T10:57:39.816Z] Missing header in: mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFile.groovy
`

2023-03-20 15:08 UTC, joe-crawford commented on mdm-security/grails-app/views/themeImageFile/index.gson
> +}
Are the views in mdm-security needed?

I'm also not sure that the index view is ever used however probably doesn't do any harm to leave it in mdm-core.

2023-03-20 15:44 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            resource = themeImageFileService.findByApiPropertyId(params.apiPropertyId)
ApiProperty added

2023-03-20 15:45 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            return
Again, ApiProperty added as suggested

2023-03-20 15:46 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    }
Yes. Removed debug code.

2023-03-20 15:50 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (saveResult && saveResult.Id && params.apiPropertyId) {
Typo fixed.

2023-03-20 15:52 UTC, NigelPalmer commented on mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/file/ThemeImageFileControllerSpec.groovy
> +                apiProperty.lastUpdatedBy = updatedBy
Updated as suggested

2023-03-20 16:04 UTC, NigelPalmer commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
>      }
I've removed the return value of instance from save, update and delete in EditLoggingController, and replicated the new versions of these methods at the higher level. I have also removed the default parameter.

2023-03-20 16:20 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    private void saveApiProperty(String apiPropertyId, String value = null) {
No. When saveApiProperty is called from delete the value is not passed in because there is no value (it's been deleted). In that case the value is null and the apiProperty value will be saved as "USE DEFAULT IMAGE". This is important for the fornt end to know whether it is loading a default or not.

2023-03-20 16:26 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    private void saveApiProperty(String apiPropertyId, String value = null) {
Ah yes, just meant that the function type could use UUIDs as 'USE DEFAULT IMAGE' is inside here.

2023-03-20 16:27 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
>      }
Great, thanks, sorry about the confusion!

2023-03-21 08:07 UTC, NigelPalmer commented on mdm-security/grails-app/views/themeImageFile/index.gson
> +}
Deleted security views. The index view was added because listAllReadableResources needed functionality added to it so it made sense to tie it all together, even though it is not currently used, it will not do any harm and may prove beneficial in the future.

2023-03-21 08:11 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> + * Copyright 2020-2023 University of Oxford and Health and Social Care Information Centre, also known as NHS Digital
Licenses updated

2023-03-21 08:12 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +        if (saveResult && saveResult.Id && params.apiPropertyId) {
Typo fix

2023-03-21 08:12 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +            return
Updated as suggested

2023-03-21 09:56 UTC, joe-crawford commented on mdm-security/grails-app/views/themeImageFile/index.gson
> +}
Great, makes sense :+1:

2023-03-22 10:40 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
>      }
Sorry @NigelPalmer I don't think the latest changes resolve this issue. I'm still getting the same error response and seeing the stacktrace after uploading a theme image file, then hitting the delete endpoint for it three times.

The issue is that the saveInstance/updateInstance/deleteInstance methods call the saveResponse/updateResponse/deleteResponse controller methods, which issue an HTTP response. If these issue a response, then the main controller method also tries to respond, the servlet gets into an inconsistent state. Also note the `validateResource` method also can issue a response and so can the `notFound` call so to make this safe, I think the only solution is make sure any validation is in the top level save/update/delete controller method, make sure there is always a return from the controller when any `notFound` is used, and don't call any response method inside the `*Instance` methods; these should just do the relevant action only.

2023-03-22 10:42 UTC, joe-crawford requested changes

2023-03-22 10:42 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    }
Please see comment above about the `*Instance` methods calling the `*Response` methods.

2023-03-22 10:59 UTC, joe-crawford commented on mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/core/file/ThemeImageFileFunctionalSpec.groovy
> +        assert ApiProperty.count() == 45
This is giving
```
Condition not satisfied:

ApiProperty.count() == 45
|           |       |
|           20      false
class uk.ac.ox.softeng.maurodatamapper.core.admin.ApiProperty

2023-03-22 11:09 UTC, joe-crawford commented on mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/test/SecurityUsers.groovy
> +        createModernSecurityUsers(creatorKey, includeAdmin)
This change is making the security unit tests fail, could you revert if not needed.

2023-03-22 11:48 UTC, NigelPalmer commented on mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/test/SecurityUsers.groovy
> +        createModernSecurityUsers(creatorKey, includeAdmin)
Apologies. I meant to revert that since it is not required. Now reverted.

2023-03-27 07:01 UTC, NigelPalmer commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
>      }
I have reworked the code so that the methods always return a HTTP response.

2023-03-27 07:03 UTC, NigelPalmer commented on mdm-security/grails-app/views/themeImageFile/index.gson
> +}
Re-added security views. The tests show that the code is insisting on using the security views. This is a bit odd. For the sake of getting this code complete, I think we should leave this in place for now and come back to it later. If you agree?

2023-03-27 07:04 UTC, NigelPalmer commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file/ThemeImageFileController.groovy
> +    }
Reworked code to always return a HTTP Response.

2023-03-27 07:06 UTC, NigelPalmer commented on mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/core/file/ThemeImageFileFunctionalSpec.groovy
> +        assert ApiProperty.count() == 45
I was including a reference to mdm-plugin-explorer in my local build. This was causing the tests to run with different data. I removed the reference, and then was able to align the tests with how they run in Jenkins.

2023-03-27 11:15 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/controller/EditLoggingController.groovy
>      }
@NigelPalmer, great, thanks for that.

2023-03-27 11:16 UTC, joe-crawford commented on mdm-security/grails-app/views/themeImageFile/index.gson
> +}
@NigelPalmer, yes I agree, definitely fine to leave this for now :)

Perhaps all the tests in security for this could actually be in core but I don't think it's doing any harm and can see they are all passing :)

2023-03-27 11:17 UTC, joe-crawford commented on mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/test/SecurityUsers.groovy
> +        createModernSecurityUsers(creatorKey, includeAdmin)
No worries.

2023-03-27 11:18 UTC, joe-crawford approved these changes
@NigelPalmer, thanks for this great piece of work which has taken a lot of effort! All tests are passing, and the code and API all looks good :+1:

2023-03-27 11:18 UTC, merged