GH-416 Add show superceded document search filter
MauroDataMapper/mdm-core pull request #424
Opened 2023-06-15 18:54 UTC by GBishop-PHSA

gh-416 Addition of a search parameter to determine whether superceded document version should be included in search results.

2023-06-26 14:28 UTC, joe-crawford requested changes
Hi Gail, thanks a lot for this, definitely looks useful. Sorry for the delay, I've just got back from leave.

Could you have a look at the comments, mostly about the superceded owning items and update or let us know what you think.

2023-06-26 14:28 UTC, joe-crawford commented on mdm-core/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/core/rest/transport/search/SearchParams.groovy
> +    Boolean supercededDocuments
Can I suggest this is changed to "includeSuperceded" rather than "supercededDocuments". Reason being is that in the past 'document version' was added as a separate version feature, now we are mainly trying to move away from using it and just use the main version functionality.

I can see this change looks at both the document version and the model version, which is good.

2023-06-26 14:28 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/search/AbstractCatalogueItemSearchService.groovy
> +            items.removeIf {it.id in getExcludedCatalogueItemIds(searchParams, items)}
I've tried this out on the default test/development DB:

When searching for "version tree", I get 9 models when 'Show superceded' = false, 13 when 'Show superceded' = true, which looks right.

When searching for "modify data class", I always get 13 data class results when 'Show superceded' is true and false. However some of these are contained within the superceded data models. I think the items in superceded parents should probably also be excluded? Probably something could be added to `getFilteredDomainsToSearch`.

2023-06-26 14:28 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/search/AbstractCatalogueItemSearchService.groovy
> +            log.error("Superceded Param: {}", searchParams.supercededDocuments);
Could you reduce the logging level to `log.debug`, thanks.

2023-07-26 23:20 UTC, GBishop-PHSA commented
@joe-crawford  I've updated the search to remove catalogue items where the parent model is a superceded version and reduced the logging level

2023-08-04 18:29 UTC, joe-crawford commented
@GBishop-PHSA That's great. Thanks again for this contribution.

2023-08-04 18:29 UTC, joe-crawford approved these changes

2023-08-04 18:30 UTC, merged