GH-415 Include comments and files during catalogue copy
MauroDataMapper/mdm-core pull request #425
Opened 2023-06-15 22:32 UTC by GBishop-PHSA

gh-415 Addition of copying files and comments when a new version of a catalogue item is created.

2023-06-26 15:30 UTC, joe-crawford requested changes
Hi Gail, thanks for this PR, this looks really useful. Sorry again for the delay.

Could you have a look at the comment about the child annotations, thanks.

2023-06-26 15:30 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
> +                        createdBy: copier.emailAddress, childAnnotations: it.childAnnotations)
I don't think `childAnnotations: it.childAnnotations` will work because this will point to the old annotation IDs. I've tested this and it actually removes the child annotation from the original model and moves them to the copy. This would have to do a deep copy of the child annotations and create new child Annotation objects on the copy.

2023-07-27 22:23 UTC, GBishop-PHSA commented
@joe-crawford  I've updated the copy to call the annotation service deep copy method.

2023-08-04 20:08 UTC, joe-crawford approved these changes
Great, thanks for this feature :+1:

2023-08-04 20:10 UTC, joe-crawford requested changes
Sorry @GBishop-PHSA just noticed there are some failing tests related to the Comments. Probably just needs the tests updating, could you have a look?

2023-08-11 19:01 UTC, GBishop-PHSA commented
@joe-crawford I'm not able to fix this test as it passes on my local computer:
CatalogueUserFunctionalSpec > Test exporting all Users to csv file (as admin) FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at CatalogueUserFunctionalSpec.groovy:1340

2023-08-18 10:46 UTC, joe-crawford approved these changes
Thanks for this. The tests are also passing for me locally.

I can't see the cause of the failing ones now but usually it's an unrelated Hibernate or concurrency issue.

2023-08-18 10:48 UTC, merged