gh-808 Added validation for max file size property
MauroDataMapper/mdm-core pull request #431
Opened 2023-07-24 22:59 UTC by GBishop-PHSA

gh-808 Is to add a helpful user message to the UI when a file that exceeds the maximum file size is set to be uploaded. 
Since this is set in the plugin.yml of mdm-core, the ApiPropertyService was updated to not allow a maximum file size configuration to be added that is greater than the Grails config maximum request size.

Bootstrap was also updated to set the api property, if it doesn't already exist, to a value that equals the Grails configured maximum file size.

2023-08-04 23:43 UTC, joe-crawford requested changes

2023-08-04 23:43 UTC, joe-crawford commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/admin/ApiPropertyController.groovy
> +    private Integer maxFileUploadSize;
Hi @GBishop-PHSA,

Thanks for this contribution and sorry for the delay. There are various failing tests linked to
```
Error creating bean with name 'apiPropertyService': Unsatisfied dependency expressed through field 'maxFileUploadSize'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "${grails.controllers.upload.maxFileSize}"
```.

It looks like there are issues using the Spring `@Value` annotation in Grails. Probably the easiest solution is to switch to `grailsApplication.config.getProperty`. Could you update so that the tests pass? Thanks.

2023-08-11 18:54 UTC, GBishop-PHSA commented
@joe-crawford I'm not sure why the build test isn't passing: 
DataModelFunctionalSpec > MI07 : test merge into of two DMs with a Model Data Type FAILED
   java.lang.AssertionError at DataModelFunctionalSpec.groovy:2379

It passes when I run this test locally.

2023-08-18 10:21 UTC, joe-crawford commented
> @joe-crawford I'm not sure why the build test isn't passing: DataModelFunctionalSpec > MI07 : test merge into of two DMs with a Model Data Type FAILED java.lang.AssertionError at DataModelFunctionalSpec.groovy:2379
> 
> It passes when I run this test locally.

Thanks for updating, that looks like a StaleStateException error so isn't related.

I've rebased onto develop, the new failing tests are also not related. This looks good to me, I've commented on the UI PR.

2024-04-03 21:00 UTC, GBishop-PHSA commented on mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/admin/ApiPropertyController.groovy
> +    private Integer maxFileUploadSize;
@joe-crawford I've finished updating the tests to pass.

2024-04-22 09:38 UTC, joe-crawford commented
Hi @GBishop-PHSA, many thanks for the PR, have tested successfully locally with your UI branch and seen the message when an overly large attachment is attempted.

2024-04-22 09:41 UTC, joe-crawford approved these changes

2024-04-22 09:41 UTC, merged