gh-457: Created endpoint and tests
MauroDataMapper/mdm-core pull request #465
Opened 2024-05-23 11:18 UTC by mhocc

-   The test is not currently passing and this may be because the test model is not valid.
-   Worked around the security restriction in `DataModelInterceptor`—needs reviewing
-   Noticed that copy permisssions is not implemented and will throw is requested.

The errors seem to be database related which might indicate the data model being used in the tests is the cause

2024-05-23 11:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/MauroDataMapper/mdm-core?pullRequest=465) <br/>All committers have signed the CLA.

2024-06-13 20:25 UTC, jamesrwelch commented
@pjmonks I think this looks like a sensible approach, yes 👍

2024-07-03 11:50 UTC, pjmonks requested changes
This is looking great to me! I've tested manually that I can copy a data model and terminology and this works. I wasn't able to test copying a term yet since the interceptor security is not letting me - please review my comment on that and fix.

The automated tests all look good too.

One question for @jamesrwelch and @joe-crawford - do these changes require a new available action to be returned for each resource in the `availableActions` array, such as `copy`? From previous experience fiddling with this that sounds complex and breaks lots of tests. Or could we make do with one of the existing ones, such as `save`?

2024-07-03 11:50 UTC, pjmonks commented on mdm-plugin-terminology/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermInterceptor.groovy
> +            return canEditModelAndReadOtherModel()
This isn't quite right, but the intention is correct. The URL mapping and expected request body (JSON) is this:

```
PUT /terminologies/{terminologyId}/terms/copy/{termId}

{
    "targetTerminologyId": "uuid",
    "label": "some label"
}
```

Any variables in the URL route are found in the `params` map, and anything in the request body can be found in the `request` map (I think...)

When `actionName` is `"copyTerm"`, it will need to check:

1. Can the source terminology be read? I think this is done by `currentUserSecurityPolicyManager.userCanReadSecuredResourceId(Terminology.class, params.terminologyId)`
2. Can the target terminology be edited? I think this is done by `currentUserSecurityPolicyManager.userCanEditSecuredResourceId(Terminology.class, request.targetTerminologyId)`

If either of those are `false` then return `notFound()`. It would be helpful if @joe-crawford could confirm I got this correct too.

2024-07-03 11:50 UTC, pjmonks commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/interceptor/ModelInterceptor.groovy
> +            boolean canReadModel = currentUserSecurityPolicyManager.userCanReadSecuredResourceId(getSecuredClass(), getId())
This seems correct to me 👍

2024-07-03 12:04 UTC, joe-crawford commented
> This is looking great to me! I've tested manually that I can copy a data model and terminology and this works. I wasn't able to test copying a term yet since the interceptor security is not letting me - please review my comment on that and fix.
> 
> The automated tests all look good too.
> 
> One question for @jamesrwelch and @joe-crawford - do these changes require a new available action to be returned for each resource in the `availableActions` array, such as `copy`? From previous experience fiddling with this that sounds complex and breaks lots of tests. Or could we make do with one of the existing ones, such as `save`?

Hi @pjmonks , yes aware how painful that is, definitely if we can piggy back on an existing permission/action, makes sense. Can anyone who can read the model create a copy? In that case doesn't even really need to be listed specifically?

2024-07-03 12:06 UTC, joe-crawford commented on mdm-plugin-terminology/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermInterceptor.groovy
> +            return canEditModelAndReadOtherModel()
@pjmonks Yes definitely agree with your logic above, and also agree that the canEditModelAndReadOtherModel() call won't work, the model IDs will be the wrong way round and `targetTerminologyId` won't be picked up.

2024-07-03 12:10 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/interceptor/ModelInterceptor.groovy
> +            boolean canReadModel = currentUserSecurityPolicyManager.userCanReadSecuredResourceId(getSecuredClass(), getId())
In ModelInterceptor, there's also this bit 

```
// We control addition of models into containers by using container permissions
            if (isSave()) {
                return currentUserSecurityPolicyManager.userCanCreateResourceId(Model, null, Folder, params.folderId) ?:
                       forbiddenOrNotFound(canReadFolder, Folder, params.folderId)
            }
```

which checks the parent folder is writeable, should also do a similar check when copying to a new folder. Probably can tweak this to be `isSave() || isCopy()``.

2024-07-03 12:42 UTC, pjmonks commented
> > This is looking great to me! I've tested manually that I can copy a data model and terminology and this works. I wasn't able to test copying a term yet since the interceptor security is not letting me - please review my comment on that and fix.
> > The automated tests all look good too.
> > One question for @jamesrwelch and @joe-crawford - do these changes require a new available action to be returned for each resource in the `availableActions` array, such as `copy`? From previous experience fiddling with this that sounds complex and breaks lots of tests. Or could we make do with one of the existing ones, such as `save`?
> 
> Hi @pjmonks , yes aware how painful that is, definitely if we can piggy back on an existing permission/action, makes sense. Can anyone who can read the model create a copy? In that case doesn't even really need to be listed specifically?

The key part of copying is that a user is able to create a new model/item in the target location, so it's effectively the same permission as "create" (or whatever that is called). So let's ignore an additional action then.

2024-07-04 12:15 UTC, mhocc commented on mdm-plugin-terminology/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermInterceptor.groovy
> +            return canEditModelAndReadOtherModel()
Implemented Pete's suggestion

2024-07-04 12:16 UTC, mhocc commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/interceptor/ModelInterceptor.groovy
> +            boolean canReadModel = currentUserSecurityPolicyManager.userCanReadSecuredResourceId(getSecuredClass(), getId())
Not sure if the suggested change belongs to this task.

2024-07-04 15:56 UTC, pjmonks approved these changes
Had to make a tweak to the `TermInterceptor` security again but my manual testing shows it works now. Ready to go ✔️

2024-07-05 13:35 UTC, joe-crawford commented on mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/interceptor/ModelInterceptor.groovy
> +            boolean canReadModel = currentUserSecurityPolicyManager.userCanReadSecuredResourceId(getSecuredClass(), getId())
Noted that it looks like there's a restriction to only copy models within their original versioned folder, however is there any check that the user can actually edit the versioned folder rather than just read it?

2024-07-05 13:36 UTC, joe-crawford commented on mdm-plugin-terminology/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermInterceptor.groovy
> +//            }
If it isn't possible to get the `targetTerminologyId` out in the Interceptor, it should be possible to just add the call to `currentUserSecurityPolicyManager.userCanEditSecuredResourceId(Terminology, targetTerminologyId)` directly within the controller.

2024-07-05 15:31 UTC, pjmonks commented
@joe-crawford I've added some additional security checks you requested, please can you check they're OK?

2024-07-05 16:47 UTC, pjmonks commented
Only one test failure this time, again a different test and I think due to a database error when running, so I don't think it's related to this change.

2024-07-08 09:40 UTC, joe-crawford commented
Great, thanks @pjmonks, @mhocc, looks good to me :+1:

2024-07-08 09:41 UTC, merged