Add filtering to endpoint that provides DataElements per DataModel
MauroDataMapper/mdm-core pull request #471
Opened 2024-06-28 13:02 UTC by jamesrwelch

One failing test which I think is unrelated

2024-06-28 16:09 UTC, pjmonks requested changes
Seems close, but returns an error for me, please review my comment.

2024-06-28 16:09 UTC, pjmonks commented on mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementService.groovy
> +        Map<String, Object> queryParams = [dataModelId: dataModelId]
I've spotted a problem when testing this locally. I tried `GET /dataModels/{dataModelId}/dataElements?max=20&label=accomodation` to test filtering the data element label but got a 500 response saying "Named parameter not bound : label" from Hibernate.

I compared to the data type list endpoint `GET /dataModels/{dataModelId}/dataTypes?max=20&label=abdom` which works. Comparing the `DataTypeService`, it has this line in `findAllDataTypesByHQLQuery()`:

```groovy
queryParams.putAll(extractFiltersAsHQLParameters(filters))
```

This isn't included in the `DataElementService`. So I think it's still only filtering on `dataModelId` but the HQL query now includes a `:label` parameter it cannot resolve.

2024-07-02 11:06 UTC, jamesrwelch commented
@OButlerOcc @pjmonks  I believe this is now ready for re-review.  Note the force-push after rebasing on develop.

2024-07-03 10:26 UTC, pjmonks approved these changes
I've tested your fix again and it works now. I've also pushed up my own addition, I figured out how to filter by both label for the data element and the parent data class too. If any tests fail on Jenkins I believe they will be unrelated. Ready to merge ✔️

2024-07-04 10:47 UTC, joe-crawford commented
@pjmonks, @jamesrwelch FYI I've tried running the failing tests locally, `FolderTreeItemFunctionalSpec` passed but `VersionedFolderFunctionalSpec` failed at the same test (DI06) as in Jenkins.

2024-07-04 11:11 UTC, joe-crawford commented
VersionedFolderFunctionalSpec DI06 is passing locally on develop so think something has been affected there. Not sure exactly what though.

2024-07-05 12:05 UTC, merged