Feature/mc 9325
MauroDataMapper/mdm-core pull request #65
Opened 2021-04-28 09:39 UTC by jamesrwelch

Dynamic Profiles.  Tests currently passing

2021-04-28 09:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MauroDataMapper/mdm-core?pullRequest=65) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MauroDataMapper/mdm-core?pullRequest=65) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MauroDataMapper/mdm-core?pullRequest=65) it.</sub>

2021-04-28 11:20 UTC, olliefreeman requested changes
Theres a few changes which need to be made and a few changes i think should be made

2021-04-28 11:20 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileSpecificationFieldProfileService.groovy
> +        getClass().getPackage().getSpecificationVersion() ?: 'SNAPSHOT'
i would drop this into the super class to make them all use it...slightly simpler

2021-04-28 14:24 UTC, jamesrwelch commented on mdm-plugin-profile/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/profile/ProfileFunctionalSpec.groovy
> +    "metadataNamespace":"uk.ac.ox.softeng.maurodatamapper.profile",
It was intentional... although I might see if I can make them use the same namespace - there was once some reason it didn't work nicely, but would be good to get it right before too many people start using it

2021-04-28 14:24 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        List<Metadata> metadataList = metadataService.findAllByCatalogueItemId(catalogueItem.id)
Presumably I should be using MultiFacetAware rather than CatalogueItem everywhere too...

2021-04-28 14:25 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        List<Metadata> metadataList = metadataService.findAllByCatalogueItemId(catalogueItem.id)
Since I'd like profiles to be applicable to containers

2021-04-28 14:27 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        return new ProfileProviderService<JsonProfile, CatalogueItem>() {
I'd be inclined to leave it like this now and come back to it later... at the moment it plays nicely with the existing profile services for static profiles

2021-04-28 16:48 UTC, olliefreeman commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        List<Metadata> metadataList = metadataService.findAllByCatalogueItemId(catalogueItem.id)
if so ...then yes...i would make that change

2021-05-13 19:17 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        Set<ProfileProviderService> allProfiles = profileService.getAllProfileProviderServices().findAll() {
Fixed

2021-05-13 19:17 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
>                  metadataService.delete(md, true)
Fixed

2021-05-13 19:18 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
> +        System.err.println("validating...")
Fixed

2021-05-13 19:20 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +    @Autowired
Resolved

2021-05-13 19:21 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        MetadataService metadataService = grailsApplication.mainContext.getBean('metadataService')
It's from when I tried to wire the service into the inner class, but yep, gone

2021-05-13 19:23 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        List<Metadata> metadataList = metadataService.findAllByCatalogueItemId(catalogueItem.id)
Resolved.  But we should check ClassifierService which uses it a lot.

2021-05-13 19:24 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +        return new ProfileProviderService<JsonProfile, CatalogueItem>() {
Oh, alright then.  I was pleased with how it worked... but yes, I'll concede your way is cleaner 😺

2021-05-13 19:25 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileSpecificationFieldProfileService.groovy
> +        getClass().getPackage().getSpecificationVersion() ?: 'SNAPSHOT'
Done.

2021-05-13 19:26 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +            MetadataService localMetadataService = grailsApplication.mainContext.getBean('metadataService')
It wasn't working, but it's ok now I've refactored

2021-05-13 19:27 UTC, jamesrwelch commented on mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
> +    ProfileSpecificationProfileService profileSpecificationProfileService
Weird.  Should be in the same package.  Not an issue now.

2021-05-14 10:22 UTC, olliefreeman approved these changes
looks good

2021-05-14 10:22 UTC, merged