Feature/mc 9540
MauroDataMapper/mdm-core pull request #95
Opened 2021-06-28 10:59 UTC by OButlerOcc

Bootstrap for versioning. Added a variety of bootstraped versioning elements. Primarily located in in V1, V2 and the V2 Branch. Fixed a copying issue, located another (see comment in bootstrapModels)

2021-06-28 11:02 UTC, olliefreeman commented
@gammonpeter @pjmonks can you please run this up or ask @OButlerOcc to demo it to you to see if this covers enough use cases to make your lives easier when testing the UI as this is the reason for this piece of work.

2021-06-28 11:34 UTC, pjmonks commented
@olliefreeman I've already had a demo of this work and was happy with it, assuming that @OButlerOcc added the additions we discussed last week (some rules and metadata included). If @gammonpeter wanted a look too he's welcome.

Currently only Data Models are versioned/branched in this bootstrapped data, no versioned folders yet. My suggestion to @OButlerOcc was to get the bootstrapped Data Models merged in first as a priority to assist @gammonpeter working on the new merge UI (could at least test on Data Models for now). Separately @OButlerOcc could then include versioned folders bootstrapped data to help with the merge UI for model families.

2021-06-28 12:17 UTC, olliefreeman commented
@pjmonks cool. Yes VFs will come later, this is just a DM structure for now.
@OButlerOcc will be working on DOIs next.

2021-06-28 12:36 UTC, OButlerOcc commented
Since we last reviewed pete I added the Rules you requested and ensured the metadata was available. Little unsure what happened to the metaData issue. I opened https://github.com/MauroDataMapper/mdm-ui/issues/204 in response to my investigation. James thinks it might be a backend issue in regards to the metaData Id being wrong. Do we have a working example to see if the returned ID is being mutated somewhere?

2021-06-28 12:38 UTC, olliefreeman commented
the MD issue has been moved to mdm-core as its UUID isnt rendering properly which means the correct view isnt being used by the API

2021-06-28 13:06 UTC, olliefreeman requested changes
Needs a lot of tidying up in the BootstrapModels class.
Please see the individual line comments, but basically we dont want to use any services for interations in the BM classes.
You are interacting with the models directly and therefore can use addToXxxx and removeFromXxxx and the checkAndSave. This will propagate all the necessary casacdes for saves and deletes.

Please make the requested chanegs and if you want to discuss anything to better understand my comments, msg me and we cna have a video chat

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        v2DataModel.dataClasses.remove(v1DataClass)
you are mixing and matching service and direct call methods this is unnecessary and messy.
ideally you should be able to call this one line and then save the DM without performing any other actions as the removal will cascade a deletion during saving.

if this doesnt work then you should use the DC service to delete the top DC as that WILL cascade deletion of all content and then the last line here should be to return  `DataModel.findById(v2DataModel.id)`

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        v2DataModel = DataModel.findById(v2DataModel.id)
unnecessay as we should ensire the DM being passed in is the correct one

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        checkAndSave(messageSource, v1ModifyDataClass)
as with the DC manipulation, just remove the DE and add the DEs and then checkAndSave the DC, dont use the service

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        v2DataModel.metadata.add(md1)
You should use object.addToMetadata never add directly to the collection, the addToXxxx methods set the opposiing side of the relationship

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        metadataService.delete(md2.getId())
dont use the service just use object.removeFromMetadata after finding it and then checkAndSave the dm

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        v2DataModel = DataModel.findById(v2DataModel.id)
not needed

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        v2DataModel.metadata.remove(md2)
use object.removeFromMetadata again removeFromXxxx handles gorm relationships and you should never interact with a collection directly

2021-06-28 13:06 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        checkAndSave(messageSource, v2DataModel)
as all above, dont use the service use removeFromRules then save the dm

2021-06-28 14:06 UTC, OButlerOcc commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        checkAndSave(messageSource, v2DataModel)
there is an error check that prevents this:
uk.ac.ox.softeng.maurodatamapper.api.exception.ApiInternalException: Do not use removeFrom to remove facet from domain

Seems people have got around it by using object.rules.remove is that ok in this context? This only applys to the rules facet.

2021-06-28 14:07 UTC, olliefreeman commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        checkAndSave(messageSource, v2DataModel)
can you let me know where `object.rules.remove` is used??? 
and ah yes i remember i put that exception in there...it should actually be okay to use in this context.

2021-06-28 14:11 UTC, OButlerOcc commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        checkAndSave(messageSource, v2DataModel)
Whoops I was wrong. its object.metadata.remove I got mixed up with. You're correct rules is never acted on directly.

2021-06-28 14:20 UTC, OButlerOcc commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        metadataService.delete(md2.getId())
The issue I'm having here, and why I'm using the services is they seem to clear up the breadcrumbs. If I removefrom, what do I need to do to prevent this error:

deleted object would be re-saved by cascade (remove deleted object from associations): [uk.ac.ox.softeng.maurodatamapper.core.facet.BreadcrumbTree#d0a19d1e-f6fe-4ad7-a146-f03408e3a870]

breadcrumbTree.updateTree() did not seem to solve the problem

2021-06-28 15:13 UTC, OButlerOcc commented on mdm-plugin-datamodel/grails-app/utils/uk/ac/ox/softeng/maurodatamapper/datamodel/bootstrap/BootstrapModels.groovy
> +        v2DataModel.dataClasses.remove(v1DataClass)
due to the breadcrumb cascade issue I'm using the services for dataClass and dataElement to handle the clean up, let me know if you want that done a different way

2021-06-29 12:31 UTC, olliefreeman approved these changes
Once this passes tests i'm happy

2021-06-30 20:46 UTC, merged